### ISSUE TITLE
adhiya Android App

### ISSUE THREAD

**Issue by sivarajadurai** [payilagam-java/login-apk#1]
http://adhiyafinance.com/
Ad111
arivu

Need to work on the below option
- borrower
- Collection

**Comment by sivarajadurai** [comment]
[Uploading project.pptx…]()

**Comment by sivarajadurai** [comment]
1. Logo can be anything related to finance
2. Change the name "Adhiya"
3. Add browwer and detail page
4. Clone the project from  
https://github.com/payilagam-java/login-apk.git

**Comment by sivarajadurai** [comment]
> 1. Logo can be anything related to finance
> 
>     2. Chang the name "Adhiya"

**Comment by sivarajadurai** [comment]
1. Logo is very small in the rounded background
![image](https://github.com/payilagam-java/login-apk/assets/20918460/8850499c-7bfe-4a22-ad38-2fd83cbb23ac)
2. Change the app name  as "Adhiya".
3. Place only logo in the splash screen and login screen. 
4. Remove the "ADHIYA FINANCE LTD" in login screen.
5. Remove the below screen 
![image](https://github.com/payilagam-java/login-apk/assets/20918460/abd3ad16-19c6-46d7-82e2-4a5a69711c12)

**Comment by Ayyappan-E** [comment]
Done

**Comment by sivarajadurai** [comment]
Change the app name as "Adhiya". - Name is not change,. You need to modify string.xml file
Work on the displaying borrower list page.

**Comment by Ayyappan-E** [comment]
app name change completed
