### ISSUE TITLE
API Testing

### ISSUE THREAD

**Issue by sivarajadurai** [payilagam-java/login-apk#4]
Create document for API testing for below details

baseurl : http://arivukarasu-002-site1.ltempurl.com/

Login:
baseurl/api/AccessToken/GetAccessToken

Modules:
baseurl/api/GetMasterPage

Borrower:
get - baseurl/api/Borrower/GetBorrower
add/edit - baseurl/api/Borrower/InsertUpdateBorrower
delete - baseurl/api/Borrower/DeleteBorrower

BorrowerLoan:
get - baseurl/api/Loan/GetBorrowerLoan
add/edit - baseurl/api/Loan/InsertUpdateBorrowerLoan
LoanStatusChange - baseurl/api/Loan/ChangeBorrowerLoanStatus

BorrowerLoanHistory:
get - baseurl/api/Loan/GetBorrowerLoanHistory

CollectionBoard:
get - baseurl/api/Collection/GetCollection
Pay/edit - baseurl/api/Collection/InsertUpdateCollection

LineExpense:
get - baseurl/api/Collection/GetLineExpense
add/edit - baseurl/api/Collection/InsertUpdateExpense
delete - baseurl/api/Collection/DeleteLineExpense

**EXAMPLE**:
**URL** : http://arivukarasu-002-site1.ltempurl.com/api/AccessToken/GetAccessToken
**Request** : 
{
    "Password":"Arivu@123",
    "UserId":"Ad112",
    "ApiKey":"zdeftryuioplmnbhg"
}
**Response Code** : 200
**Response**:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWQxMTIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3NlcmlhbG51bWJlciI6IjcwMzgiLCJleHAiOjE3MjA0MTQ3OTcsImlzcyI6IlRlc3QuY29tIiwiYXVkIjoiVGVzdC5jb20ifQ.n3YeuyPa5GqV7rWe2vceu8KTDcYKh20QuxSZ-96xbO4

**Comment by vivethaitech** [comment]
[API TESTING.odt](https://github.com/user-attachments/files/16216028/API.TESTING.odt)

**Comment by sivarajadurai** [comment]
Good work
