### ISSUE TITLE
apk Testing

### ISSUE THREAD

**Issue by vivethaitech** [payilagam-java/login-apk#8]
1.After logged in, the app look like blank with only plus icon
![photo_6149881143802053478_y](https://github.com/user-attachments/assets/b994311d-7c7b-4915-a1f6-efe3268d4447)

2. Whenever I click select line, there is no option showing to select
![photo_6149881143802053483_y](https://github.com/user-attachments/assets/f2ba38c1-a5c9-4928-93b9-a541529dcede)

3.Whenever I click referred by option,  select one only showing
![photo_6149881143802053488_y](https://github.com/user-attachments/assets/87fcd1cf-60a2-45c9-8368-b63822dc481a)

**Comment by sivarajadurai** [comment]
the above issue got fixed.
